### ISSUE TITLE
New application cookbook/checklist

### ISSUE THREAD

**Issue by charypar** [Financial-Times/next#86]
This is about the 3rd or 4th time I'm starting a new Next application and I still feel like I have no idea what I'm doing and would appreciate an exhaustive checklist of things to do.

Below I'll put my idea of what such a list would look like as I'm starting an application (some of it are steps from http://financial-times.github.io/next/docs/developer-guide/creating-new-apps/). I'm sure I missed a lot in the first punt, feel free to amend.
## New app Checklist
- [ ] create a GitHub repo, make sure to add `next` team as Admins
- [ ] `npm init`, clean up `package.json`
- [ ] dependencies `npm install --save ft-next-express`
- [ ] dev dependencies `npm install --save-dev next-build-tools`
- [ ] Basic project structure: `server/app.js`, (`client/`, `views/`)
- [ ] make sure your server handles at least `/` and `/__gtg` urls
- [ ] Makefile based on one of the next apps (at least `make install`, `make run` and `make test`)
- [ ] steal `.env` file from a next app if you need api keys, etc.
- [ ] steal a `circle.yml` file from a next app
- [ ] add pre-test (`make build-production test`) command in Circle project settings (is there an automation around this I missed?)
- [ ] steal a `Procfile` file from a next app and `npm install --save forever`
## Deploy Checklist
- [ ] create a new app [in Sentry](https://app.getsentry.com/nextftcom/)
- [ ] add required environment variables to `config-vars` repo (this will now update `.env` on `nbt run`) including the Sentry url as `RAVEN_URL`
- [ ] `nbt download-development-keys` to fetch the new shiny config vars in development
- [ ] create heroku app `heroku create YOUR_APP_NAME --region eu --org financial-times`
- [ ] `nbt configure` to push the config vars
- [ ] add `make build-production` with minimum `nbt about` and `make deploy` with `nbt configure` and `nbt deploy` to your Makefile
- [ ] add `make provision` and `make tidy` to do a test deploy as part of the build (see a next app's Makefile for how that works). Run `make provision` as pre-test and `make tidy` as post-test in Circle. **can't get this to work, for some reason it just hangs creating the app**
- [ ] add `HEROKU_AUTH_TOKEN` environment variable with an authorised token (`heroku auth:token` to find out yours) in CircleCI project configuration
- [ ] register app in the next registry.  Don't add paths for something that isn't user facing.
## Platinum Checklist
- [ ] configure multi-region (how?)
- [ ] get a domain name (where?) and point int to fastly
- [ ] deploy an appropriate VCL file pointing fastly to your heroku app
